### ISSUE TITLE
When the submission is too big would be great to test files locally 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-curation-scripts#1]
Sometimes the NFS file system is really slow and the validation is really slow for big submissions. Especially the XML validation is really slow because the xml needs to be validated with the XSD. We need to create a mechanism to validate locally and also in local nodes the xmls.

**Comment by deeptijk** [comment]
@yprivero - I am still not able to do the XML Validation, as it is not possible to do it on local machine because it's big and every time it's looses the connection it breaks. I tried in server but still the problem is same. I want to find a way to submit it as a job to server so that it don't get killed and finish the Validation.

**Comment by ypriverol** [comment]
One possible option is to move one mzIdnetML to your local machine. The other is to lunch the job using the script from @sureshhewabi . What do you think?

**Comment by deeptijk** [comment]
I already tried it on my machine but still it breaks every time I close the lid.

**Comment by sureshhewabi** [comment]
xmllint --schema mzIdentML1.1.0.xsd Mascot_MSMS_example.mzid --noout --output output.txt > output_file.txt 2>&1

**Comment by deeptijk** [comment]
Thanks ... It's solved now
