### ISSUE TITLE
Bug in the Submission Tool

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#22]
We have bug in the tool. Once you upload the file and try to add the relations between the files by clicking add relations button, it opens the window, but the moment you click on add/deselect button, it goes to zero, and it doesn't allow you do anything now.

**Comment by sureshhewabi** [comment]
This issue happens when user tries to upload zipped raw files(which is not a recommended way). I have fixed the issue in the upcoming release. Therefore, We need to ask user to upload unzipped raw files and proceed with the submission. If it is not possible, I will do a new release in Submission tool with this fix.

**Comment by sureshhewabi** [comment]
Today after having a discussion with Yasset, We decided that 

- We allow only zip and gzip compressions(no .rar etc allowed)
- .RAW/.raw from Thermo shouldn't be compressed, Other files are allowed to compress
