### ISSUE TITLE
Problem with the download

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#25]
Individual download link is not working for this project link -

http://ftp.pride.ebi.ac.uk/pride/data/archive/2018/12/PXD007662/20161223_Qp2_02_SI_T1.pep.xml

**Comment by sureshhewabi** [comment]
If you check any other files, they can be downloaded by clicking on the file. But files that have only pep.xml cannot be downloaded like that. 

The reason for this is, some browsers tries to render XML file in the browser and tries to show the xml file in the browser. For example, if you click on a HTML file, it directly open and render the content to browser. XML also have a same behaviour. So not only it tries to load, but also will start rendering it. Since pep.xml large in size(~50MB in 20161223_Qp2_02_SI_T1.pep.xml file) browser get crashed or it will take significant time to load. It is not reccomend to open such a big file in a browser too.

There are three alternative ways to download files

**by Right-click and save link as option**

![Screen Shot 2019-04-18 at 11 27 27](https://user-images.githubusercontent.com/5387193/56355007-1d57e400-61cd-11e9-8711-934a92f5ced8.png)


**from FTP download option**

![Screen Shot 2019-04-18 at 11 12 20](https://user-images.githubusercontent.com/5387193/56354239-20ea6b80-61cb-11e9-8cfa-deb60269f326.png)


**from command-line**
`curl ’http://ftp.pride.ebi.ac.uk/pride/data/archive/2018/12/PXD007662/20161223_Qp2_02_SI_T1.pep.xml' -o ~/Downloads/20161223_Qp2_02_SI_T1.pep.xml`

**Comment by sureshhewabi** [comment]
@deeptijk Can we close this?

**Comment by deeptijk** [comment]
Yes
