### ISSUE TITLE
Issue with PX Tool : File mapping issue

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-curation-scripts#33]
Any missing file mapping issues are not reported in log files of the PX tool.

**Comment by sureshhewabi** [comment]
<img width="912" alt="Screen Shot 2019-09-13 at 12 13 55 PM" src="https://user-images.githubusercontent.com/5387193/64858709-099b9700-d620-11e9-8158-2245d02b4754.png">

The issue here is, when user maps many raw files, if they missed a one or two then it is difficult to find out which one is not mapped. Therefore, files that are not mapped should be written to logs

**Comment by sureshhewabi** [comment]
![Screen Shot 2019-09-13 at 12 16 50 PM](https://user-images.githubusercontent.com/5387193/64858954-c7bf2080-d620-11e9-8434-74076c43e008.png)
